# Generated by Django 4.2.6 on 2023-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='experiance',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Entry Level', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
