# Generated by Django 4.2.6 on 2023-10-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_freelancer_about_freelancer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
