# Generated by Django 4.2.6 on 2023-10-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_freelancer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnames',
            name='jobcategory',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
