# Generated by Django 4.2.6 on 2023-10-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_jobnames_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jobnames'),
        ),
        migrations.AlterField(
            model_name='jobnames',
            name='jobcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
